### ISSUE TITLE
permission denied to push

### ISSUE THREAD

**Issue by Ledoux** [betagouv/fetch-normalize-data#50]
Hello @jdauphant 

je pense que j'ai perdu depuis peu mes droits pour pousser (et plus généralement mes droits admin) sur les repos suivants :
- https://github.com/betagouv/fetch-normalize-data
- https://github.com/betagouv/redux-thunk-data
- https://github.com/betagouv/sqlalchemy-api-handler
- https://github.com/betagouv/with-react-redux-login
- https://github.com/betagouv/with-react-formidable
- https://github.com/betagouv/redux-react-modals

Tu penses que je pourrais récuperer ces droits s'il te plait ?

Merci beaucoup,

**Comment by jdauphant** [comment]
Salut @Ledoux ,

C'est bon, je t'ai mis en contributeur externe sur les projets.
On a un bot qui pilote les entrées-sorties de l'organisation maintenant.

Bonne soirée,
Julien
